apiVersion: v1
kind: Service
metadata:
  labels:
    app: stock-app
  name: stock-app
spec:
  ports:
    - name: 15002-tcp
      port: 15002
      protocol: TCP
      targetPort: 15002
  selector:
    app: stock-app
  sessionAffinity: None
  type: ClusterIP
