name: Build & publish images
on: [push]

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup maven
        uses: s4u/setup-maven-action@v1.5.0
        with:
          java-version: 17
          
      - name: Build and push order app container
        run: cd ./order-app && mvn -DskipTests spring-boot:build-image
      - name: Build and push payment app container
        run: cd ./payment-app && mvn -DskipTests spring-boot:build-image
      - name: Build and push stock app container
        run: cd ./stock-app && mvn -DskipTests spring-boot:build-image
